In [10]:
import pandas as pd
import numpy as np

In [11]:
df = pd.read_csv("multiTimeline (1).csv")
df.columns

Index(['Week', 'Asha Bhosle', 'Mohammed Rafi', 'Kishore Kumar', 'Kumar Sanu',
       'Alka Yagnik'],
      dtype='object')

In [12]:
df["Week"] = pd.to_datetime(df["Week"])
df.set_index("Week", inplace=True)

print("Original Dataset:")
df

Original Dataset:

/var/folders/fc/b_3ntmtx3kv_43ckpdzjd47r0000gn/T/ipykernel_7322/2592771221.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df["Week"] = pd.to_datetime(df["Week"])

            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-02-10           16             56             63          59           20
2019-02-17           15             51             60          58           21
2019-02-24           14             45             55          54           21
2019-03-03           14             52             62          60           23
2019-03-10           16             51             69          54           21
...                 ...            ...            ...         ...          ...
2023-12-31           15             37             47          29           18
2024-01-07           14             36             41          29           17
2024-01-14           12             34             42          27           16
2024-01-21           11             31             39          25           15
2024-01-28           12             31             42          28           19

[260 rows x 5 columns]

In [13]:
# Resample to daily frequency (up-sampling with forward fill)
daily_data = df.resample('D').ffill()

# Display the up-sampled daily dataset
print("\nUp-sampled Daily Dataset with Forward Fill:")
print(daily_data)

Up-sampled Daily Dataset with Forward Fill:
            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-02-10           16             56             63          59           20
2019-02-11           16             56             63          59           20
2019-02-12           16             56             63          59           20
2019-02-13           16             56             63          59           20
2019-02-14           16             56             63          59           20
...                 ...            ...            ...         ...          ...
2024-01-24           11             31             39          25           15
2024-01-25           11             31             39          25           15
2024-01-26           11             31             39          25           15
2024-01-27           11             31             39          25           15
2024-01-28           12             31             42          28           19

[1814 rows x 5 columns]

In [14]:
# Resample to monthly frequency (down-sampling with OHLC)
monthly_data = df.resample('M').ohlc()

# Display the down-sampled monthly dataset
print("\nDown-sampled Monthly Dataset with OHLC:")
print(monthly_data)

Down-sampled Monthly Dataset with OHLC:
           Asha Bhosle                Mohammed Rafi                 \
                  open high low close          open high low close
Week
2019-02-28          16   16  14    14            56   56  45    45
2019-03-31          14   16  13    15            52   52  47    48
2019-04-30          13   15  13    14            48   53  47    53
2019-05-31          14   14  10    14            44   55  44    55
2019-06-30          17   17  15    15            58   59  55    55
2019-07-31          14   19  14    17            63   69  63    66
2019-08-31          16   16  12    14            55   66  55    66
2019-09-30          11   19   9    14            57   66  45    45
2019-10-31          15   17  11    11            63   68  46    56
2019-11-30           8   23   8    17            64   67  64    67
2019-12-31          16   21  12    12            51   59  45    57
2020-01-31          24   24  10    10            62   63  54    55
2020-02-29          12   19  12    15            55   67  55    62
2020-03-31          12   22  12    12            71   71  44    47
2020-04-30          21   25  14    25            49   49  44    49
2020-05-31          13   14  11    11            39   51  39    51
2020-06-30          15   15   9    15            52   54  52    53
2020-07-31          14   14  11    14            63   64  55    64
2020-08-31          13   14  13    14            66   66  59    64
2020-09-30          24   24  14    15            68   73  68    72
2020-10-31          17   21  14    21            67   71  66    71
2020-11-30          15   19  15    19            68   74  65    72
2020-12-31          18   20  15    18            73   76  70    70
2021-01-31          17   18  16    16            71   76  67    76
2021-02-28          15   19  15    19            74   75  64    74
2021-03-31          21   23  18    21            65   68  54    54
2021-04-30          21   21  19    20            66   66  49    55
2021-05-31          17   22  16    19            56   73  56    69
2021-06-30          20   21  16    16            69   74  65    74
2021-07-31          22   32  19    19            74   74  60    72
2021-08-31          19   20  19    19            69   70  57    69
2021-09-30          24   24  17    17            59   66  59    60
2021-10-31          15   21  15    20            68   74  63    74
2021-11-30          22   22  18    18            66   66  62    64
2021-12-31          30   30  22    25            70   70  63    67
2022-01-31          26   26  18    25            68   74  61    74
2022-02-28          36   36  17    21            74   76  60    69
2022-03-31          22   22  16    17            66   66  62    62
2022-04-30          18   23  16    23            48   57  48    57
2022-05-31          18   19  14    14            55   55  39    44
2022-06-30          14   14  12    13            44   44  38    38
2022-07-31          14   17  14    17            38   46  37    46
2022-08-31          17   17  15    15            39   42  38    38
2022-09-30          17   17  11    11            39   41  38    38
2022-10-31          13   15  12    15            38   43  38    42
2022-11-30          14   19  14    19            38   44  38    44
2022-12-31          18   18  16    16            40   44  40    44
2023-01-31          16   16  15    15            40   40  35    36
2023-02-28          14   14  12    14            36   36  33    34
2023-03-31          13   13  12    12            31   34  27    27
2023-04-30          10   12  10    11            28   34  28    34
2023-05-31           9   13   9    13            35   39  35    35
2023-06-30          13   13  12    12            35   36  34    34
2023-07-31          12   13  11    13            33   42  32    42
2023-08-31          15   15  12    13            38   38  34    36
2023-09-30          16   16  14    14            32   33  30    33
2023-10-31          13   13  11    13            34   34  28    33
2023-11-30          14   14  11    14            33   34  33    33
2023-12-31          14   16  14    15            35   40  35    37
2024-01-31          14   14  11    12            36   36  31    31

           Kishore Kumar                Kumar Sanu                Alka Yagnik  \
                    open high low close       open high low close        open
Week
2019-02-28            63   63  55    55         59   59  54    54          20
2019-03-31            62   69  59    63         60   60  48    53          23
2019-04-30            65   81  62    70         48   51  46    46          21
2019-05-31            75   83  72    76         51   78  51    78          23
2019-06-30            77   94  76    76         59   66  52    52          27
2019-07-31            76   78  70    70         62   63  59    63          26
2019-08-31            78   80  73    73         59   59  55    55          30
2019-09-30            65   74  63    65         51   60  51    57          23
2019-10-31            73   87  67    67         59   59  48    59          33
2019-11-30            97   97  80    80         43   61  43    61          27
2019-12-31            91  100  73    95         52   62  51    61          27
2020-01-31            78   93  78    86         54   59  49    49          31
2020-02-29            73   95  73    95         58   59  47    58          25
2020-03-31            94   94  76    76         47   47  31    42          16
2020-04-30            74   77  64    74         45   51  40    40          21
2020-05-31            51   57  50    57         36   41  33    35          22
2020-06-30            54   69  51    69         42   42  38    39          25
2020-07-31            56   59  56    59         42   42  38    42          26
2020-08-31            64   64  62    63         44   44  35    38          25
2020-09-30            70   70  61    70         40   43  37    43          27
2020-10-31            67   67  57    64         45   60  45    60          30
2020-11-30            70   76  66    71         58   58  40    40          27
2020-12-31            67   73  67    69         45   45  39    41          30
2021-01-31            72   72  67    72         50   59  39    59          27
2021-02-28            77   85  71    80         48   48  43    46          31
2021-03-31            67   75  59    59         39   45  36    36          24
2021-04-30            68   68  56    62         38   44  33    33          24
2021-05-31            69   97  69    75         33   48  33    43          22
2021-06-30            72   83  71    83         38   65  38    47          23
2021-07-31            80   80  68    76         49   49  39    44          26
2021-08-31            76   76  67    71         43   43  40    42          22
2021-09-30            63   70  63    69         45   49  38    49          24
2021-10-31            67   77  67    72         50   58  44    50          29
2021-11-30            71   84  71    77         55   55  47    47          29
2021-12-31            76   83  73    73         48   52  48    50          29
2022-01-31            70   73  66    70         50   50  37    44          28
2022-02-28            75   75  66    66         46   46  42    43          26
2022-03-31            64   67  58    67         41   43  39    39          27
2022-04-30            52   70  52    70         30   41  30    38          19
2022-05-31            62   62  55    55         35   35  33    33          22
2022-06-30            55   55  51    53         34   34  31    31          22
2022-07-31            55   65  49    65         30   32  28    32          18
2022-08-31            54   54  45    45         33   33  29    29          17
2022-09-30            47   53  43    43         28   34  28    29          16
2022-10-31            49   60  49    58         30   36  30    31          16
2022-11-30            52   55  52    55         32   35  32    35          18
2022-12-31            50   54  50    54         34   35  33    34          20
2023-01-31            48   48  43    45         32   32  28    29          17
2023-02-28            44   44  41    42         31   31  27    29          17
2023-03-31            42   44  40    40         27   29  25    25          16
2023-04-30            42   43  40    43         26   28  25    27          15
2023-05-31            45   46  43    43         27   29  27    29          17
2023-06-30            43   45  43    43         31   31  26    26          16
2023-07-31            45   51  42    51         31   31  29    30          34
2023-08-31            48   48  41    43         30   30  27    27          22
2023-09-30            39   40  39    40         25   25  23    23          19
2023-10-31            44   44  33    44         26   36  26    34          20
2023-11-30            47   47  44    44         36   36  30    32          20
2023-12-31            42   49  42    47         32   32  29    29          17
2024-01-31            41   42  39    42         29   29  25    28          17


           high low close
Week
2019-02-28   21  20    21
2019-03-31   23  18    21
2019-04-30   23  21    23
2019-05-31   27  23    27
2019-06-30   30  22    29
2019-07-31   33  26    33
2019-08-31   33  28    33
2019-09-30   34  23    30
2019-10-31   33  20    24
2019-11-30   27  15    22
2019-12-31   34  17    24
2020-01-31   34  24    24
2020-02-29   25  16    23
2020-03-31   28  16    19
2020-04-30   21  12    19
2020-05-31   27  22    23
2020-06-30   25  23    23
2020-07-31   28  25    27
2020-08-31   32  20    32
2020-09-30   29  21    29
2020-10-31   30  27    28
2020-11-30   30  25    27
2020-12-31   30  23    24
2021-01-31   35  25    35
2021-02-28   31  28    28
2021-03-31   28  22    22
2021-04-30   27  22    22
2021-05-31   24  18    24
2021-06-30   26  23    24
2021-07-31   26  22    24
2021-08-31   23  22    23
2021-09-30   29  22    25
2021-10-31   38  25    29
2021-11-30   29  25    28
2021-12-31   32  29    30
2022-01-31   28  22    22
2022-02-28   30  23    23
2022-03-31   27  22    25
2022-04-30   26  19    24
2022-05-31   22  19    19
2022-06-30   22  20    20
2022-07-31   20  16    20
2022-08-31   18  15    15
2022-09-30   17  16    16
2022-10-31   18  16    17
2022-11-30   18  17    18
2022-12-31   20  17    18
2023-01-31   21  17    21
2023-02-28   17  15    15
2023-03-31   17  15    15
2023-04-30   20  15    15
2023-05-31   21  17    19
2023-06-30   18  16    17
2023-07-31   34  22    22
2023-08-31   22  20    22
2023-09-30   21  16    17
2023-10-31   20  17    19
2023-11-30   20  17    19
2023-12-31   18  16    18
2024-01-31   19  15    19

/var/folders/fc/b_3ntmtx3kv_43ckpdzjd47r0000gn/T/ipykernel_7322/3098476574.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_data = df.resample('M').ohlc()

In [15]:
# Shift the time series forward and backward using naive shifts
shifted_forward = df.shift(2)
shifted_backward = df.shift(-2)

# Display the shifted datasets
print("\nShifted Forward Dataset:")
print(shifted_forward)
print("\nShifted Backward Dataset:")
print(shifted_backward)

Shifted Forward Dataset:
            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-02-10          NaN            NaN            NaN         NaN          NaN
2019-02-17          NaN            NaN            NaN         NaN          NaN
2019-02-24         16.0           56.0           63.0        59.0         20.0
2019-03-03         15.0           51.0           60.0        58.0         21.0
2019-03-10         14.0           45.0           55.0        54.0         21.0
...                 ...            ...            ...         ...          ...
2023-12-31         15.0           37.0           46.0        32.0         18.0
2024-01-07         14.0           40.0           49.0        31.0         16.0
2024-01-14         15.0           37.0           47.0        29.0         18.0
2024-01-21         14.0           36.0           41.0        29.0         17.0
2024-01-28         12.0           34.0           42.0        27.0         16.0

[260 rows x 5 columns]

Shifted Backward Dataset:
            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-02-10         14.0           45.0           55.0        54.0         21.0
2019-02-17         14.0           52.0           62.0        60.0         23.0
2019-02-24         16.0           51.0           69.0        54.0         21.0
2019-03-03         16.0           52.0           64.0        53.0         22.0
2019-03-10         13.0           47.0           59.0        48.0         18.0
...                 ...            ...            ...         ...          ...
2023-12-31         12.0           34.0           42.0        27.0         16.0
2024-01-07         11.0           31.0           39.0        25.0         15.0
2024-01-14         12.0           31.0           42.0        28.0         19.0
2024-01-21          NaN            NaN            NaN         NaN          NaN
2024-01-28          NaN            NaN            NaN         NaN          NaN

[260 rows x 5 columns]

In [17]:
# Shift the time series forward and backward using frequency
shifted_forward_freq = df.shift(2, freq='W')
shifted_backward_freq = df.shift(-2, freq='W')

# Display the frequency-shifted datasets
print("\nFrequency Shifted Forward Dataset:")
print(shifted_forward_freq)
print("\nFrequency Shifted Backward Dataset:")
print(shifted_backward_freq)

Frequency Shifted Forward Dataset:
            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-02-24           16             56             63          59           20
2019-03-03           15             51             60          58           21
2019-03-10           14             45             55          54           21
2019-03-17           14             52             62          60           23
2019-03-24           16             51             69          54           21
...                 ...            ...            ...         ...          ...
2024-01-14           15             37             47          29           18
2024-01-21           14             36             41          29           17
2024-01-28           12             34             42          27           16
2024-02-04           11             31             39          25           15
2024-02-11           12             31             42          28           19

[260 rows x 5 columns]

Frequency Shifted Backward Dataset:
            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-01-27           16             56             63          59           20
2019-02-03           15             51             60          58           21
2019-02-10           14             45             55          54           21
2019-02-17           14             52             62          60           23
2019-02-24           16             51             69          54           21
...                 ...            ...            ...         ...          ...
2023-12-17           15             37             47          29           18
2023-12-24           14             36             41          29           17
2023-12-31           12             34             42          27           16
2024-01-07           11             31             39          25           15
2024-01-14           12             31             42          28           19

[260 rows x 5 columns]

In [18]:
# Compute moving averages using three different window functions
rolling_mean_3 = df.rolling(window=3).mean()
rolling_sum_4 = df.rolling(window=4).sum()
rolling_expanding = df.expanding().mean()

# Display the computed moving averages
print("\nMoving Average (Window=3):")
print(rolling_mean_3)
print("\nRolling Sum (Window=4):")
print(rolling_sum_4)
print("\nExpanding Mean:")
print(rolling_expanding)

Moving Average (Window=3):
            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-02-10          NaN            NaN            NaN         NaN          NaN
2019-02-17          NaN            NaN            NaN         NaN          NaN
2019-02-24    15.000000      50.666667      59.333333   57.000000    20.666667
2019-03-03    14.333333      49.333333      59.000000   57.333333    21.666667
2019-03-10    14.666667      49.333333      62.000000   56.000000    21.666667
...                 ...            ...            ...         ...          ...
2023-12-31    14.666667      38.000000      47.333333   30.666667    17.333333
2024-01-07    14.333333      37.666667      45.666667   29.666667    17.000000
2024-01-14    13.666667      35.666667      43.333333   28.333333    17.000000
2024-01-21    12.333333      33.666667      40.666667   27.000000    16.000000
2024-01-28    11.666667      32.000000      41.000000   26.666667    16.666667

[260 rows x 5 columns]

Rolling Sum (Window=4):
            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-02-10          NaN            NaN            NaN         NaN          NaN
2019-02-17          NaN            NaN            NaN         NaN          NaN
2019-02-24          NaN            NaN            NaN         NaN          NaN
2019-03-03         59.0          204.0          240.0       231.0         85.0
2019-03-10         59.0          199.0          246.0       226.0         86.0
...                 ...            ...            ...         ...          ...
2023-12-31         60.0          149.0          187.0       124.0         70.0
2024-01-07         58.0          150.0          183.0       121.0         69.0
2024-01-14         55.0          147.0          179.0       116.0         67.0
2024-01-21         52.0          138.0          169.0       110.0         66.0
2024-01-28         49.0          132.0          164.0       109.0         67.0

[260 rows x 5 columns]

Expanding Mean:
            Asha Bhosle  Mohammed Rafi  Kishore Kumar  Kumar Sanu  Alka Yagnik
Week
2019-02-10    16.000000      56.000000      63.000000   59.000000    20.000000
2019-02-17    15.500000      53.500000      61.500000   58.500000    20.500000
2019-02-24    15.000000      50.666667      59.333333   57.000000    20.666667
2019-03-03    14.750000      51.000000      60.000000   57.750000    21.250000
2019-03-10    15.000000      51.000000      61.800000   57.000000    21.200000
...                 ...            ...            ...         ...          ...
2023-12-31    16.074219      52.890625      63.160156   41.542969    22.898438
2024-01-07    16.066148      52.824903      63.073930   41.494163    22.875486
2024-01-14    16.050388      52.751938      62.992248   41.437984    22.848837
2024-01-21    16.030888      52.667954      62.899614   41.374517    22.818533
2024-01-28    16.015385      52.584615      62.819231   41.323077    22.803846

[260 rows x 5 columns]